// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBlock = "blocks"

// Block mapped from table <blocks>
type Block struct {
	Key     string `gorm:"column:key;primaryKey" json:"key"`
	GoodsID string `gorm:"column:goods_id;primaryKey" json:"goods_id"`
}

// TableName Block's table name
func (*Block) TableName() string {
	return TableNameBlock
}
