// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSlide = "slides"

// Slide mapped from table <slides>
type Slide struct {
	GoodsID string `gorm:"column:goods_id;primaryKey" json:"goods_id"`
}

// TableName Slide's table name
func (*Slide) TableName() string {
	return TableNameSlide
}
