// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q       = new(Query)
	Account *account
	Block   *block
	Good    *good
	Slide   *slide
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Account = &Q.Account
	Block = &Q.Block
	Good = &Q.Good
	Slide = &Q.Slide
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:      db,
		Account: newAccount(db, opts...),
		Block:   newBlock(db, opts...),
		Good:    newGood(db, opts...),
		Slide:   newSlide(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Account account
	Block   block
	Good    good
	Slide   slide
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:      db,
		Account: q.Account.clone(db),
		Block:   q.Block.clone(db),
		Good:    q.Good.clone(db),
		Slide:   q.Slide.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:      db,
		Account: q.Account.replaceDB(db),
		Block:   q.Block.replaceDB(db),
		Good:    q.Good.replaceDB(db),
		Slide:   q.Slide.replaceDB(db),
	}
}

type queryCtx struct {
	Account *accountDo
	Block   *blockDo
	Good    *goodDo
	Slide   *slideDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Account: q.Account.WithContext(ctx),
		Block:   q.Block.WithContext(ctx),
		Good:    q.Good.WithContext(ctx),
		Slide:   q.Slide.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	return &QueryTx{q.clone(q.db.Begin(opts...))}
}

type QueryTx struct{ *Query }

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
