// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"server/logic/orm/model"
)

func newSlide(db *gorm.DB, opts ...gen.DOOption) slide {
	_slide := slide{}

	_slide.slideDo.UseDB(db, opts...)
	_slide.slideDo.UseModel(&model.Slide{})

	tableName := _slide.slideDo.TableName()
	_slide.ALL = field.NewAsterisk(tableName)
	_slide.GoodsID = field.NewString(tableName, "goods_id")

	_slide.fillFieldMap()

	return _slide
}

type slide struct {
	slideDo

	ALL     field.Asterisk
	GoodsID field.String

	fieldMap map[string]field.Expr
}

func (s slide) Table(newTableName string) *slide {
	s.slideDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s slide) As(alias string) *slide {
	s.slideDo.DO = *(s.slideDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *slide) updateTableName(table string) *slide {
	s.ALL = field.NewAsterisk(table)
	s.GoodsID = field.NewString(table, "goods_id")

	s.fillFieldMap()

	return s
}

func (s *slide) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *slide) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 1)
	s.fieldMap["goods_id"] = s.GoodsID
}

func (s slide) clone(db *gorm.DB) slide {
	s.slideDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s slide) replaceDB(db *gorm.DB) slide {
	s.slideDo.ReplaceDB(db)
	return s
}

type slideDo struct{ gen.DO }

func (s slideDo) Debug() *slideDo {
	return s.withDO(s.DO.Debug())
}

func (s slideDo) WithContext(ctx context.Context) *slideDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s slideDo) ReadDB() *slideDo {
	return s.Clauses(dbresolver.Read)
}

func (s slideDo) WriteDB() *slideDo {
	return s.Clauses(dbresolver.Write)
}

func (s slideDo) Session(config *gorm.Session) *slideDo {
	return s.withDO(s.DO.Session(config))
}

func (s slideDo) Clauses(conds ...clause.Expression) *slideDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s slideDo) Returning(value interface{}, columns ...string) *slideDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s slideDo) Not(conds ...gen.Condition) *slideDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s slideDo) Or(conds ...gen.Condition) *slideDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s slideDo) Select(conds ...field.Expr) *slideDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s slideDo) Where(conds ...gen.Condition) *slideDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s slideDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *slideDo {
	return s.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (s slideDo) Order(conds ...field.Expr) *slideDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s slideDo) Distinct(cols ...field.Expr) *slideDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s slideDo) Omit(cols ...field.Expr) *slideDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s slideDo) Join(table schema.Tabler, on ...field.Expr) *slideDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s slideDo) LeftJoin(table schema.Tabler, on ...field.Expr) *slideDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s slideDo) RightJoin(table schema.Tabler, on ...field.Expr) *slideDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s slideDo) Group(cols ...field.Expr) *slideDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s slideDo) Having(conds ...gen.Condition) *slideDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s slideDo) Limit(limit int) *slideDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s slideDo) Offset(offset int) *slideDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s slideDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *slideDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s slideDo) Unscoped() *slideDo {
	return s.withDO(s.DO.Unscoped())
}

func (s slideDo) Create(values ...*model.Slide) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s slideDo) CreateInBatches(values []*model.Slide, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s slideDo) Save(values ...*model.Slide) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s slideDo) First() (*model.Slide, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Slide), nil
	}
}

func (s slideDo) Take() (*model.Slide, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Slide), nil
	}
}

func (s slideDo) Last() (*model.Slide, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Slide), nil
	}
}

func (s slideDo) Find() ([]*model.Slide, error) {
	result, err := s.DO.Find()
	return result.([]*model.Slide), err
}

func (s slideDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Slide, err error) {
	buf := make([]*model.Slide, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s slideDo) FindInBatches(result *[]*model.Slide, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s slideDo) Attrs(attrs ...field.AssignExpr) *slideDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s slideDo) Assign(attrs ...field.AssignExpr) *slideDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s slideDo) Joins(fields ...field.RelationField) *slideDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s slideDo) Preload(fields ...field.RelationField) *slideDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s slideDo) FirstOrInit() (*model.Slide, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Slide), nil
	}
}

func (s slideDo) FirstOrCreate() (*model.Slide, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Slide), nil
	}
}

func (s slideDo) FindByPage(offset int, limit int) (result []*model.Slide, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s slideDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s slideDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s slideDo) Delete(models ...*model.Slide) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *slideDo) withDO(do gen.Dao) *slideDo {
	s.DO = *do.(*gen.DO)
	return s
}
